# Generated by Django 6.1 on 2026-08-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_text', models.CharField(max_length=255, verbose_name='Some text ?')),
                ('time_start', models.DateTimeField()),
                ('time_stop', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Any comments')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.categoryoption')),
            ],
        ),
    ]
