# Generated by Django 6.1 on 2026-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrajLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kha_paya_gya_tha', models.CharField(max_length=255, verbose_name="Vraj's kha paya gya tha")),
                ('kis_jagah', models.CharField(max_length=255, verbose_name='kis jagah')),
                ('time_kya_tha', models.DateTimeField(verbose_name='time kya tha')),
            ],
        ),
    ]
